<?php

    namespace Delivery\NovaPoshta;


    class Counterparties extends Models\Counterparty implements \Delivery\NovaPoshta\API\NovaPoshtaApiGet, \Delivery\NovaPoshta\API\NovaPoshtaApiSUD
    {
        /**
         * @inheritDoc
         */
        public function get($isUsePageCounter = false)
        {
            return $this->getCounterparties($isUsePageCounter);
        }

        /**
         * @inheritDoc
         */
        public function save($params)
        {
            return parent::save($params); // TODO: Change the autogenerated stub
        }

        /**
         * @inheritDoc
         */
        public function update($params)
        {
            return parent::update($params); // TODO: Change the autogenerated stub
        }

        /**
         * @inheritDoc
         */
        public function delete($params)
        {
            return parent::delete($params); // TODO: Change the autogenerated stub
        }

        /**
         * getCounterpartyContactPersons() function of model Counterparty.
         *
         * @param array $params
         *
         * @return array
         */
        public function getContactPersons($params)
        {
            return $this->getCounterpartyContactPersons($params);
        }
    }
