<?php

    namespace Delivery\NovaPoshta;

    class InternetDocuments extends Models\InternetDocument implements \Delivery\NovaPoshta\API\NovaPoshtaAPIGet, \Delivery\NovaPoshta\API\NovaPoshtaApiSUD, \Delivery\NovaPoshta\API\NovaPoshtaApiPrinting
    {

        /**
         * @inheritDoc
         */
        public function get($isUsePageCounter = false)
        {
            return $this->getDocumentList($isUsePageCounter);
        }

        /**
         * @inheritDoc
         */
        public function save($params)
        {
            return parent::save($params); // TODO: Change the autogenerated stub
        }

        /**
         * @inheritDoc
         */
        public function update($params)
        {
            return parent::update($params); // TODO: Change the autogenerated stub
        }

        /**
         * @inheritDoc
         */
        public function delete($refs)
        {
            return parent::delete($refs); // TODO: Change the autogenerated stub
        }

        /**
         * @inheritDoc
         */
        public function _print($refs, $type)
        {
            return $this->printGet($refs, $type);
        }
    }
